version: '3'

services:
  app:
    container_name: app-cms
    build:
      context: ./docker
      dockerfile: Dockerfile
    image: laravel:base
    working_dir: /var/www
    restart: unless-stopped
    ports:
      - "8001:80"
    volumes:
      - ./:/var/www
    networks:
      - network

  mysql:
    container_name: mysql-cms
    image: mysql:8
    restart: unless-stopped
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - network

networks:
  network:
    driver: bridge

volumes:
  mysql:
    driver: local
